language: generic
services:
    - docker

before_install:
    - docker build -t bgpark82/react-test -f ./client/Dockerfile.dev

script:
    - docker run -e CI=true bgpark82/react-test npm run test

after_success:
    - docker build -t bgpark82/multi-client ./client
    - docker build -t bgpark82/multi-nginx ./nginx
    - docker build -t bgpark82/multi-server ./server
    - docker build -t bgpark82/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push bgpark82/multi-client
    - docker push bgpark82/multi-nginx
    - docker push bgpark82/multi-server
    - docker push bgpark82/multi-worker
